### ISSUE TITLE
The service "report_import.ezv" has a dependency on a non-existent parameter "report". Did you mean this: "report_path"?

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/ariiportal.github.io#1]
![report](https://cloud.githubusercontent.com/assets/11269587/12983302/02d5e41a-d0e9-11e5-857a-127db20ceff3.png)
La dernière fois que je me suis heurté à ce problème de configuration qui change, 
j'ai soumis un schéma à JF afin de favoriser la circulation de l'information et de définir un cycle de qualification/pré-industrialisation clair tent dans le temps que sur la méthode.

Je suis bloquer et je doit livrer, merci de me fournir le fichier de configuration adapté.

**Comment by AriiPortal** [comment]
Le problème est à voir autrement, si il manque un paramètre sur un module, est ce que le module est vraiment nécessaire ? Si non, le module est supprimé du kernel.
Si oui, il suffit de rajouter ce paramètre dans le fichier de configuration:

```
    Report:
        IPAM:
            login:     
            password:  
        EZV:
            server:    
            login:     
            password:  
```

Ces paramètres sont utilisés pour des connecteurs IPAM (gestion réseau) et EasyVista (CMDB). Je regarde pour mettre en place une activation des connecteurs comme c'est le cas pour les modules.
